READMEを更新
Shingo2023/SongMemoApp2 pull request #2
Opened 2024-07-08 08:46 UTC by Shingo2023

2024-07-08 11:47 UTC, LunaChevalier requested changes
先ほど相談されていた箇所以外でもエラーが発生していたので、そちらにもコメントしました!

2024-07-08 11:47 UTC, LunaChevalier commented on SongMemoApp2/LyricsEditViewController.swift
> +}
![should](https://img.shields.io/badge/review-should-orange.svg)
この部分は不要です
あるとエラーになるので、削除してください

2024-07-08 11:47 UTC, LunaChevalier commented on SongMemoApp2/HomeViewController.swift
> +    let storyboard = UIStoryboard(name: "Main", bundle: nil)
```suggestion
    let storyboard = UIStoryboard(name: "ActionEditViewController", bundle: nil)
```

上記が正しいです
`Main`のStorybardには`ActionEditViewController`が存在しないので、このボタンをタップするとエラーにになります

2024-07-09 15:37 UTC, Shingo2023 commented on SongMemoApp2/LyricsEditViewController.swift
> +}
削除します。

2024-07-09 15:37 UTC, Shingo2023 commented on SongMemoApp2/HomeViewController.swift
> +    let storyboard = UIStoryboard(name: "Main", bundle: nil)
こちらも変更しました。

2024-07-09 15:37 UTC, merged